"""migration3

Revision ID: 948f4c46b40f
Revises: a4db5e6b11f0
Create Date: 2026-02-01 00:08:30.250867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '948f4c46b40f'
down_revision: Union[str, Sequence[str], None] = 'a4db5e6b11f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees_orm', sa.Column('description', sa.String(), nullable=True))
    op.alter_column('employees_orm', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("TIMEZONE('utc', now() + interval '1 day')"),
               existing_nullable=False)
    op.alter_column('resumes_orm', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("TIMEZONE('utc', now() + interval '1 day')"),
               existing_nullable=False)
    op.alter_column('vacancies_orm', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("TIMEZONE('utc', now() + interval '1 day')"),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vacancies_orm', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("timezone('utc'::text, now())"),
               existing_nullable=False)
    op.alter_column('resumes_orm', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("timezone('utc'::text, now())"),
               existing_nullable=False)
    op.alter_column('employees_orm', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("timezone('utc'::text, now())"),
               existing_nullable=False)
    op.drop_column('employees_orm', 'description')
    # ### end Alembic commands ###
