"""migration2

Revision ID: a4db5e6b11f0
Revises: f7e8618c8c68
Create Date: 2026-01-31 23:56:36.168276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4db5e6b11f0'
down_revision: Union[str, Sequence[str], None] = 'f7e8618c8c68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('employees_orm', sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False))
    op.add_column('employees_orm', sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False))
    op.add_column('vacancies_orm', sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False))
    op.add_column('vacancies_orm', sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancies_orm', 'updated_at')
    op.drop_column('vacancies_orm', 'created_at')
    op.drop_column('employees_orm', 'updated_at')
    op.drop_column('employees_orm', 'created_at')
    op.drop_column('employees', 'age')
    # ### end Alembic commands ###
